### ISSUE TITLE
Empty language list on second run

### ISSUE THREAD

**Issue by jpnurmi** [canonical/ubuntu-desktop-installer#1782]
Close and re-run the installer. Only reproducible in the live session.

A regression caused by:
- https://github.com/canonical/ubuntu-desktop-installer/pull/1773

```
flutter: ERROR ubuntu_desktop_installer: Unhandled exception
	UnsupportedError: Unsupported operation: Infinity or NaN toInt
#0      RenderBox.size (package:flutter/src/rendering/box.dart)
#1      _PositionedListState._schedulePositionNotificationUpdate.<anonymous closure> (package:scrollable_positioned_list/src/positioned_list.dart:338)
#2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289)
#3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227)
#4      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:942)
#5      _rootRun (dart:async/zone.dart:1390)
#6      _CustomZone.run (dart:async/zone.dart:1300)
#7      _CustomZone.runGuarded (dart:async/zone.dart:1208)
#8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1248)
#9      _rootRun (dart:async/zone.dart:1398)
#10     _CustomZone.run (dart:async/zone.dart:1300)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232)
#12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18)
#13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#15     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

![image](https://user-images.githubusercontent.com/140617/230041583-b8801696-2096-4938-af21-00a7a46d61e7.png)

**Comment by jpnurmi** [comment]
It's empty even after closing the installer, hiding the dock again, and re-login. The only practical difference is that subiquity is already up and running at startup time.
