### ISSUE TITLE
mantic canary image - install using TPM backed encryption does not start

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [canonical/ubuntu-desktop-installer#2149]
This is in the mantic canary image.

VM, TPM and UEFI enabled, trying "Enhanced secure-boot" with TPM-backed FDE, I get this trace:
```
2023-06-21 10:06:09.735784 DEBUG subiquity_client: POST http://localhost/storage/v2/guided
2023-06-21 10:06:09.751055 ERROR ubuntu_desktop_installer: Unhandled exception
	SubiquityException: setGuidedStorageV2({"target":{"disk_id":"disk-vdb","allowed":["DIRECT","LVM","LVM_LUKS","CORE_BOOT_PREFER_ENCRYPTED"],"disallowed":[],"$type":"GuidedStorageTargetReformat"},"capability":"CORE_BOOT_ENCRYPTED","password":null,"sizing_policy":"ALL","reset_partition":false}) returned error 500
Traceback (most recent call last):
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/common/api/server.py", line 160, in handler
    result = await implementation(**args)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/controllers/filesystem.py", line 996, in v2_guided_POST
    await self.guided(data)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/controllers/filesystem.py", line 549, in guided
    await self.guided_core_boot(disk)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/controllers/filesystem.py", line 704, in guided_core_boot
    await self._mount_systems_dir(self._info.name)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/controllers/filesystem.py", line 265, in _mount_systems_dir
    self.app.controllers.Source.get_handler(variation_name)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/controllers/source.py", line 139, in get_handler
    sanitize_source(self.model.get_source(variation_name)))
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/models/source.py", line 109, in get_source
    variation = self.current.variations[variation_name]
KeyError: 'enhanced-secureboot'

#0      SubiquityClient._receive (package:subiquity_client/src/client.dart:70)
<asynchronous suspension>
#1      DiskStorageService.setGuidedStorage (package:ubuntu_desktop_installer/services/disk_storage_service.dart:101)
<asynchronous suspension>
#2      WriteChangesToDiskModel.init (package:ubuntu_desktop_installer/pages/write_changes_to_disk/write_changes_to_disk_model.dart:35)
<asynchronous suspension>
```
See installer logs:

[subiquity-logs.tar.gz](https://github.com/canonical/ubuntu-desktop-installer/files/11816376/subiquity-logs.tar.gz)

**Comment by alfonsosanchezbeato** [comment]
This seems to happen only when choosing "Minimal install"

**Comment by xnox** [comment]
I don't believe we can support "Minimal install" with FDE yet, as we don't actually have a "Minimal" model for FDE - I.e. the one without desktop snaps (?!) Unless all the desktop snaps seeded in the FDE model are usually also made available in the minimal installs already today.

**Comment by jibel** [comment]
Minimal as been removed. Only normal is available and is also hidden. I'm closing this report.
