### ISSUE TITLE
mantic canary image - install using Enhanced secure-boot fails to finish

### ISSUE THREAD

**Issue by alfonsosanchezbeato** [canonical/ubuntu-desktop-installer#2150]
This is with the mantic canary image.

VM with UEFI enabled, but no TPM and trying "Enhanced secure-boot". I see this error:
```
2023-06-21 10:30:37,839 INFO root:37 start: subiquity/Install/install/curtin_install: installing system
2023-06-21 10:30:40,680 ERROR subiquity.server.controllers.oem:79 Failed to cleanup overlay. Continuing anyway.
Traceback (most recent call last):
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/apt.py", line 270, in overlay
    await self.mounter.unmount(
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/mounter.py", line 148, in unmount
    await self.app.command_runner.run(
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/runner.py", line 92, in run
    return await self.wait(proc)
  File "/snap/ubuntu-desktop-installer/1081/bin/subiquity/subiquity/server/runner.py", line 84, in wait
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['systemd-run', '--wait', '--same-dir', '--property', 'SyslogIdentifier=subiquity_log.1838', '--setenv', 'PATH=/snap/ubuntu-desktop-installer/1081/bin/subiquity/bin:/snap/ubuntu-desktop-installer/1081/bin/subiquity/usr/bin:/snap/ubuntu-desktop-installer/1081/bin:/snap/ubuntu-desktop-installer/1081/sbin:/snap/ubuntu-desktop-installer/1081/usr/sbin:/snap/ubuntu-desktop-installer/1081/usr/bin:/snap/ubuntu-desktop-installer/1081/sbin:/snap/ubuntu-desktop-installer/1081/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', '--setenv', 'PYTHONPATH=/snap/ubuntu-desktop-installer/1081/lib/python3.10/site-packages:/snap/ubuntu-desktop-installer/1081/usr/lib/python3/dist-packages:/snap/ubuntu-desktop-installer/1081/usr/lib/python3/site-packages:', '--setenv', 'PYTHON=/snap/ubuntu-desktop-installer/1081/usr/bin/python3.10', '--setenv', 'SNAP=/snap/ubuntu-desktop-installer/1081', '--', 'umount', '/tmp/tmp7xehuamc/mount']' returned non-zero exit status 32.
```
See logs:

[subiquity-logs2.tar.gz](https://github.com/canonical/ubuntu-desktop-installer/files/11816697/subiquity-logs2.tar.gz)

**Comment by jibel** [comment]
It is not possible to do an enhanced-secureboot installation without a TPM. The option is not available in this case.
I'm closing this report. 

Do not hesitate to reopen if it is still an issue.
