### ISSUE TITLE
subiquity fails on zfs disk partitioning

### ISSUE THREAD

**Issue by tim-hm** [canonical/ubuntu-desktop-installer#2312]
## Background

ZFS support is being added for 23.10 (both in subiquity and the desktop installer). For 23.10 ZFS encryption is not supported.

Cross posted to https://bugs.launchpad.net/subiquity/+bug/2033043

## Issue

This is on mantic daily (25 Aug 2023), running installer 0+git.1792d817, x1 carbon gen9.

When selecting ZFS disk partitioning subiquity fails when installing grub to target. Extract from subiquity logs:

```text
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Running command ['umount', '/target/dev'] with allowed return codes [0] (capture=False)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         finish: cmd-install/stage-curthooks/builtin/cmd-curthooks/install-grub: FAIL: installing grub to target devices
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         finish: cmd-install/stage-curthooks/builtin/cmd-curthooks/configuring-bootloader: FAIL: configuring target system bootloader
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         finish: cmd-install/stage-curthooks/builtin/cmd-curthooks: FAIL: curtin command curthooks
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Traceback (most recent call last):
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/commands/main.py", line 202, in main
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             ret = args.func(args)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/commands/curthooks.py", line 1933, in curthooks
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             builtin_curthooks(cfg, target, state)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/commands/curthooks.py", line 1898, in builtin_curthooks
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             setup_grub(cfg, target, osfamily=osfamily,
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/commands/curthooks.py", line 836, in setup_grub
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             install_grub(instdevs, target, uefi=uefi_bootable, grubcfg=grubcfg)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/commands/install_grub.py", line 451, in install_grub
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             in_chroot.subp(cmd, env=env, capture=True)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/util.py", line 791, in subp
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             return subp(*args, **kwargs)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/util.py", line 283, in subp
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             return _subp(*args, **kwargs)
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:           File "/snap/ubuntu-desktop-installer/1202/lib/python3.10/site-packages/curtin/util.py", line 147, in _subp
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:             raise ProcessExecutionError(stdout=out, stderr=err,
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         curtin.util.ProcessExecutionError: Unexpected error while running command.
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Command: ['unshare', '--fork', '--pid', '--', 'chroot', '/target', 'update-grub']
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Exit code: 1
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Reason: -
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Stdout: ''
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Stderr: Sourcing file `/etc/default/grub'
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 Sourcing file `/etc/default/grub.d/init-select.cfg'
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 Generating grub configuration file ...
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 /etc/grub.d/10_linux_zfs: 425: version_find_latest: not found
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 umount: /tmp/zfsmnt.sVyvTn: target is busy.
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 rmdir: failed to remove '/tmp/zfsmnt.sVyvTn': Device or resource busy
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Unexpected error while running command.
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Command: ['unshare', '--fork', '--pid', '--', 'chroot', '/target', 'update-grub']
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Exit code: 1
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Reason: -
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Stdout: ''
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         Stderr: Sourcing file `/etc/default/grub'
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 Sourcing file `/etc/default/grub.d/init-select.cfg'
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 Generating grub configuration file ...
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 /etc/grub.d/10_linux_zfs: 425: version_find_latest: not found
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 umount: /tmp/zfsmnt.sVyvTn: target is busy.
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 rmdir: failed to remove '/tmp/zfsmnt.sVyvTn': Device or resource busy
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:                 
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         {'current': '001D', 'timeout': '0 seconds', 'order': '001D,0000,0010,0011,0012,0013,0014,0015,0016,001A,001B,001C,001E,001F,0020,0021,0022'}
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         {'current': '001D', 'timeout': '0 seconds', 'order': '001D,0000,0010,0011,0012,0013,0014,0015,0016,001A,001B,001C,001E,001F,0020,0021,0022'}
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]:         
Aug 25 10:01:37 ubuntu subiquity_log.5305[13012]: Stderr: ''
```

**Comment by jibel** [comment]
Thanks for your report.
This is actually a bug in grub that is being worked on https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/2029260
