### ISSUE TITLE
[Log Warning] Try Ubuntu: Exception caught by gesture

### ISSUE THREAD

**Issue by ItzSwirlz** [canonical/ubuntu-desktop-installer#5]
```
══╡ EXCEPTION CAUGHT BY GESTURE
╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Could not find a generator for route RouteSettings("/tryubuntu", null) in the
_WidgetsAppState.
Make sure your root app widget has provided a way to generate
this route.
Generators for routes are searched for in the following order:
 1. For the "/" route, the "home" property, if non-null, is used.
 2. Otherwise, the "routes" table is used, if it has an entry for the route.
 3. Otherwise, onGenerateRoute is called. It should return a non-null value for
 any valid route not
handled by "home" and "routes".
 4. Finally if all else fails onUnknownRoute is called.
Unfortunately, onUnknownRoute was not set.

When the exception was thrown, this was the stack:
#0      _WidgetsAppState._onUnknownRoute.<anonymous closure>
(package:flutter/src/widgets/app.dart:1219:9)
#1      _WidgetsAppState._onUnknownRoute
(package:flutter/src/widgets/app.dart:1234:6)
#2      NavigatorState._routeNamed
(package:flutter/src/widgets/navigator.dart:4148:37)
#3      NavigatorState.pushNamed
(package:flutter/src/widgets/navigator.dart:4190:20)
#4      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:1726:34)
#5      TryOrInstallPageState.continueWithSelectedOption
(package:ubuntu_desktop_installer/tryorinstallpage.dart:153:17)
#6      _InkResponseState._handleTap
(package:flutter/src/material/ink_well.dart:991:20)
#7      GestureRecognizer.invokeCallback
(package:flutter/src/gestures/recognizer.dart:182:24)
#8      TapGestureRecognizer.handleTapUp
(package:flutter/src/gestures/tap.dart:607:11)
#9      BaseTapGestureRecognizer._checkUp
(package:flutter/src/gestures/tap.dart:296:5)
#10     BaseTapGestureRecognizer.handlePrimaryPointer
(package:flutter/src/gestures/tap.dart:230:7)
#11     PrimaryPointerGestureRecognizer.handleEvent
(package:flutter/src/gestures/recognizer.dart:475:9)
#12     PointerRouter._dispatch
(package:flutter/src/gestures/pointer_router.dart:93:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:138:9)
#14     _LinkedHashMapMixin.forEach
(dart:collection-patch/compact_hash.dart:397:8)
#15     PointerRouter._dispatchEventToRoutes
(package:flutter/src/gestures/pointer_router.dart:136:18)
#16     PointerRouter.route
(package:flutter/src/gestures/pointer_router.dart:122:7)
#17     GestureBinding.handleEvent
(package:flutter/src/gestures/binding.dart:381:19)
#18     GestureBinding.dispatchEvent
(package:flutter/src/gestures/binding.dart:361:22)
#19     RendererBinding.dispatchEvent
(package:flutter/src/rendering/binding.dart:278:11)
#20     GestureBinding._handlePointerEventImmediately
(package:flutter/src/gestures/binding.dart:316:7)
#21     GestureBinding.handlePointerEvent
(package:flutter/src/gestures/binding.dart:280:5)
#22     GestureBinding._flushPointerEventQueue
(package:flutter/src/gestures/binding.dart:238:7)
#23     GestureBinding._handlePointerDataPacket
(package:flutter/src/gestures/binding.dart:221:7)
#27     _invoke1 (dart:ui/hooks.dart:180:10)
#28     PlatformDispatcher._dispatchPointerDataPacket
(dart:ui/platform_dispatcher.dart:276:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:96:31)
(elided 3 frames from dart:async)

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#84574
════════════════════════════════════════════════════════════════════════════════
════════════════════

```

**Comment by oSoMoN** [comment]
Thanks for the report. The "Try Ubuntu" option is simply not implemented at this point, so that's an expected exception.
Keep in mind that this is a very early prototype and very little is actually implemented. That said, testing and feedback is always welcome!
