### ISSUE TITLE
Installer Broken 17th January Canary Image

### ISSUE THREAD

**Issue by bittin** [canonical/ubuntu-desktop-installer#616]
Hello!

The installer, does not all work to install anything with yet, tested in a Virtualbox VM atleast the 86% Swedish looks good 
the daily image with the older installer works however

**Comment by bittin** [comment]
![VirtualBox_Ubuntu Installer Test_17_01_2022_16_19_15](https://user-images.githubusercontent.com/43197/149796310-4476eac1-a161-47fe-83d3-5d194e114e0c.png)

Screenshot and Error log attached: https://pastebin.com/u57Mgqn0 as @seb128 wanted

**Comment by jpnurmi** [comment]
We should have a fix available soon.

In `/var/log/installer/subiquity-server-debug.log`:
```
ERROR root:39 finish: subiquity/Install/install: FAIL: can only concatenate str (not "list") to str
```

**Comment by bittin** [comment]
next log @seb128 requested: https://pastebin.pl/view/4f4abe49

**Comment by jpnurmi** [comment]
Probably a matter of updating subiquity: https://github.com/canonical/subiquity/pull/1161

**Comment by bittin** [comment]
@jpnurmi thanks, will try with next weeks canary test ISO then and hope it works better then

**Comment by jpnurmi** [comment]
canonical/subiquity#1161 helped with the str concatenation issue. The next issue is:
```
2022-01-17 16:05:20,511 ERROR subiquity.server.server:405 top level error
Traceback (most recent call last):
  File "/snap/ubuntu-desktop-installer/x1/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/snap/ubuntu-desktop-installer/x1/bin/subiquity/subiquitycore/async_helpers.py", line 26, in _done
    fut.result()
  File "/snap/ubuntu-desktop-installer/x1/bin/subiquity/subiquity/server/controllers/mirror.py", line 137, in _apply_apt_config
    await self.apt_configurer.cleanup()
  File "/snap/ubuntu-desktop-installer/x1/bin/subiquity/subiquity/server/apt.py", line 229, in cleanup
    shutil.rmtree(d)
  File "/snap/ubuntu-desktop-installer/x1/usr/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/snap/ubuntu-desktop-installer/x1/usr/lib/python3.8/shutil.py", line 659, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/snap/ubuntu-desktop-installer/x1/usr/lib/python3.8/shutil.py", line 657, in _rmtree_safe_fd
    os.rmdir(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: 'mount'
```
There's an unmerged fix available: canonical/subiquity#1163

**Comment by bittin** [comment]
Still broken for me with the 25th January 2022 Canary ISO

**Comment by jpnurmi** [comment]
Could you share some details and logs? 20220125 installs fine for me.

![20220125_1](https://user-images.githubusercontent.com/140617/150972354-afcff40d-a118-4610-b4ab-f3e4c99d4ce5.png)
![20220125_2](https://user-images.githubusercontent.com/140617/150972435-a49fbb3e-a117-4b8d-a57f-df4de3fe6d77.png)
![20220125_3](https://user-images.githubusercontent.com/140617/150972544-cf22d4b0-5ddb-46a1-9bc0-6bbe8e560819.png)

**Comment by bittin** [comment]
Works with the 30th January 2020 Build, have not been able to test before today
